---
- name: Déployer le Backend Spring Boot
  hosts: k8s_master
  become: no
  vars:
    kube_namespace: "default"
    kubeconfig: "/home/ammar/.kube/config"

  tasks:

    - name: Vérifier la connexion au cluster
      command: kubectl cluster-info
      environment:
        KUBECONFIG: "{{ kubeconfig }}"
      register: cluster_info

    - name: Afficher l'état du cluster
      debug:
        msg: "{{ cluster_info.stdout }}"

    - name: Copier le manifest backend deployment
      copy:
        src: /home/ammar/deploy-app-spring-angular/k8s/deploy-spring.yaml
        dest: /tmp/backend-deployment.yaml
        remote_src: yes

    - name: Copier le manifest backend service
      copy:
        src: /home/ammar/deploy-app-spring-angular/k8s/spring-service.yaml
        dest: /tmp/backend-service.yaml
        remote_src: yes

    - name: Appliquer le deployment backend
      command: kubectl apply -f /tmp/backend-deployment.yaml -n {{ kube_namespace }}
      environment:
        KUBECONFIG: "{{ kubeconfig }}"

    - name: Appliquer le service backend
      command: kubectl apply -f /tmp/backend-service.yaml -n {{ kube_namespace }}
      environment:
        KUBECONFIG: "{{ kubeconfig }}"

    - name: Attendre que le déploiement soit prêt
      command: kubectl rollout status deployment/spring-boot-deployment -n {{ kube_namespace }}
      environment:
        KUBECONFIG: "{{ kubeconfig }}"
      retries: 5
      delay: 10

    - name: Vérifier les pods backend
      command: kubectl get pods -l app=spring-boot-app -n {{ kube_namespace }}
      environment:
        KUBECONFIG: "{{ kubeconfig }}"
      register: pods_status

    - name: Afficher les pods
      debug:
        msg: "{{ pods_status.stdout }}"
